gui:
  showRandomTip: false
  nerdFontsVersion: "3"
  border: rounded
  sidePanelWidth: 0.25
  statusPanelView: allBranchesLog
  theme:
    activeBorderColor:
      - "#ffff00"
      - bold
    inactiveBorderColor:
      - white

git:
  pagers:
    - pager: delta --dark --paging=never --hunk-header-style=omit --file-decoration-style=none --file-style=omit --line-numbers --line-numbers-left-format="{nm:>4} " --line-numbers-right-format="{np:>4} " --line-numbers-left-style="" --line-numbers-right-style="" --line-numbers-minus-style="" --line-numbers-plus-style="" --line-numbers-zero-style="" --keep-plus-minus-markers --syntax-theme="Visual Studio Dark+" --side-by-side
  diffContextSize: 15
