gui:
  showRandomTip: false
  nerdFontsVersion: "3"
  border: rounded
  sidePanelWidth: 0.25
  statusPanelView: allBranchesLog
  theme:
    activeBorderColor:
      - "#ffff00"
      - bold
    inactiveBorderColor:
      - white

git:
  pagers:
    - pager: delta
  diffContextSize: 15
