gui:
  showRandomTip: false
  nerdFontsVersion: "3"
  border: rounded
  sidePanelWidth: 0.2
  statusPanelView: allBranchesLog
  showFileTree: false
  theme:
    activeBorderColor:
      - "#ffff00"
      - bold
    inactiveBorderColor:
      - white
git:
  pagers:
    - pager: delta --paging=never
  diffContextSize: 15
keybinding:
  universal:
    goInto: '<disabled>'
    focusMainView: '<enter>'
