# Starship Configuration
# https://starship.rs/config/

add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$character"""

[character]
success_symbol = ' [\$](white)'
error_symbol = ' [\$](red)'

[directory]
truncation_length = 3
truncate_to_repo = true
format = '[$path]($style)'
style = 'blue'

[git_branch]
symbol = ''
format = ' [$branch]($style)'
style = '243'

[git_status]
disabled = true

[cmd_duration]
min_time = 2000
format = ' [$duration]($style)'
style = '243'
