# Starship Configuration
# https://starship.rs/config/

add_newline = false

format = """
$username\
$directory\
$character"""

[character]
success_symbol = ' [\$](white)'
error_symbol = ' [\$](red)'

[username]
show_always = true
format = '[$user]($style) | '
style = '243'

[directory]
truncation_length = 3
truncate_to_repo = true
format = '[$path]($style)'
style = 'blue'
